#开发环境
server:
  #端口号
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    #druid连接池
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/news?serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      #最大存活连接数
      max-active: 10
      #初始化连接个数
      initial-size: 3
      #最少连接个数
      min-idle: 3
      #最大等待时间
      max-wait: 3000
  main:
    #不显示banner
    banner-mode: off

  #redis配置
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #密码，默认为空
    #password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 1
    #连接超时时间（毫秒）
    timeout: 1000
    #数据库索引号
    database: 0

mybatis-plus:
  global-config:
    db-config:
      #表前缀
      table-prefix: tb_
      #id自增长
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
    #不显示banner
    banner: off
  configuration:
    #日志输出，控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #禁止字段名驼峰映射，不包括表名
    map-underscore-to-camel-case: false
  #别名扫包
  type-aliases-package: com.kaysen.domain
  #枚举扫包
  type-enums-package: com.kaysen.domain.enums

newsapp:
  #线程池配置
  my-executor:
    #核心线程数
    core-pool-size: 4
    #最大线程数
    max-pool-size: 10
    #等待队列容量
    queue-capacity: 10
  #天行API key
  tianxing-key: 
  mail:
    #邮件发送账户
    username: 
    #邮箱授权码
    key: 
  my-redis:
    #redis，是否开启
    state: false